

services:
  db:
    image: postgres:14-alpine
    container_name: redditlike-db
    env_file:
      - ./envs/.env.db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 2s    # Wait for n second before starting health checks
      interval: 10s       # Time between each health check
      timeout: 3s         # Time to wait for a health check to respond
      retries: 3          # Number of consecutive failures needed to consider the container as unhealthy


  backend:
    depends_on:
      db:
        condition: service_healthy
    image: onionkim/redditlike-back:v1.0
    container_name: redditlike-back
    ports:
      - "3030:3030"
      - "3031:3031"
    env_file:
      - ./envs/.env.backend

  front:
    depends_on:
      backend:
        condition: service_started
    image: onionkim/redditlike-front:v1.0
    container_name: redditlike-front
    ports:
      - "3010:3010"

volumes:
  db_data:


