export * from "./SvgIcons";


import {
  Expand as ExpandIcon,
  Add as AddIcon,
  AddCircle as AddCircleIcon,
  AddCircleOutline as AddCircleOutlineIcon,
  Menu as MenuIcon,
  ChevronLeft as ChevronLeftIcon,
  Close as CloseIcon,
  Search as SearchIcon,
  Error as ErrorIcon,
  Category as CategoryIcon,
  Portrait as FlairIcon,
  Settings as SettingIcon,
  Block as BlockIcon,
  HighlightOff as UnblockIcon,
  Notifications as NotificationIcon,
  Person as PersonIcon,
  Note as NoteIcon,
  Email as EmailIcon,
  Logout as LogoutIcon,
  History as HistoryIcon,
  ExitToApp as ExitIcon,
  ArrowForwardIos as ArrowForwardIcon,
  Check as CheckIcon,
  HighlightOff as UnpinIcon,
  Replay as RetryIcon,
  AdminPanelSettings as ManagerIcon,
  AccountCircle as AccountIcon,
  ExpandLess as FoldIcon,
  ExpandMore as UnfoldIcon,
  Label as FlagIcon,
  LocalFireDepartment as HotIcon,
  TrendingUp as TrendingIcon,
  Visibility as PreviewIcon,
  PublishedWithChanges as ReorderIcon,
  Rule as RuleIcon,
  Flaky as CensorIcon,
  CameraAltOutlined as CameraIcon,
  MarkEmailRead as EmailCheckIcon,
  CampaignOutlined as SpoilerIcon,
  VisibilityOutlined as ViewIcon,
} from "@mui/icons-material";

export {
  ExpandIcon,
  AddIcon,
  AddCircleIcon,
  AddCircleOutlineIcon,
  MenuIcon,
  ChevronLeftIcon,
  CloseIcon,
  SearchIcon,
  ErrorIcon,
  CategoryIcon,
  FlairIcon,
  SettingIcon,
  BlockIcon,
  UnblockIcon,
  NotificationIcon,
  PersonIcon,
  NoteIcon,
  EmailIcon,
  LogoutIcon,
  HistoryIcon,
  ExitIcon,
  ArrowForwardIcon,
  CheckIcon,
  UnpinIcon,
  RetryIcon,
  ManagerIcon,
  AccountIcon,
  FoldIcon,
  UnfoldIcon,
  FlagIcon,
  HotIcon,
  TrendingIcon,
  PreviewIcon,
  ReorderIcon,
  RuleIcon,
  CensorIcon,
  CameraIcon,
  EmailCheckIcon,
  SpoilerIcon,
  ViewIcon,
};


import {
  Edit as EditIcon,
  EditOutlined as EditOlIcon,
  Article as PostIcon,
  ArticleOutlined as PostOlIcon,
  ThumbsUpDown as VoteIcon,
  ThumbsUpDownOutlined as VoteOlIcon,
  Comment as CommentIcon,
  CommentOutlined as CommentOlIcon,
  Delete as DeleteIcon,
  DeleteOutline as DeleteOlIcon,
  Star as StarIcon,
  StarOutline as StarOlIcon,
  PostAdd as PostAddIcon,
  AddPhotoAlternateOutlined as PhotoAddIcon,
  VideoCallOutlined as VideoAddIcon,
  Circle as CircleIcon,
  CircleOutlined as CircleOlIcon,
  Image as ImageIcon,
  ImageOutlined as ImageOlIcon,
  AccessTime as RecentIcon,
  Restore as PastIcon,
  SubdirectoryArrowRightOutlined as NestedIcon,
  ArrowBackIos as BackIosIcon,
  ArrowForwardIos as ForwardIosIcon,
  Info as InfoIcon,
  InfoOutlined as InfoOlIcon,
  Home as HomeIcon,
  HomeOutlined as HomeOlIcon,
  Dashboard as DashboardIcon,
  DashboardOutlined as DashboardOlIcon,
  PushPin as PinIcon,
  PushPinOutlined as PinOlIcon,
  Help as HelpIcon,
  HelpOutline as HelpOlIcon,
  VideoLibrary as VideoIcon,
  VideoLibraryOutlined as VideoOlIcon,
  KeyboardArrowUp as ScrollTopIcon,
  CheckCircle as CheckCircleIcon,
  CheckCircleOutline as CheckCircleOlIcon,
  PlayCircleOutline as PlayCircleOlIcon,
  Group as GroupIcon,
  GroupOutlined as GroupOlIcon,
  Bookmark as BookmarkIcon,
  BookmarkBorder as BookmarkOlIcon,
  BookmarkRemoveOutlined as UnbookmarkOlIcon,
  Reply as ReplyIcon,
  ThumbUp as ThumbUpIcon,
  ThumbUpOutlined as ThumbUpOlIcon,
  ThumbDown as ThumbDownIcon,
  ThumbDownOutlined as ThumbDownOlIcon,
  ArrowBack as ArrowBackIcon,
  Send as SendIcon,
  CalendarMonth as CalendarIcon,
  Podcasts as LiveChatIcon,
  FormatBold as FormatBoldIcon,
  FormatUnderlined as FormatUnderlinedIcon,
  FormatItalic as FormatItalicIcon,
  FormatStrikethrough as FormatStrikeIcon,
  FormatQuote as FormatQuoteIcon,
  FormatListBulleted as FormatListButlletIcon,
  FormatListNumbered as FormatListNumberIcon,
  FormatAlignCenter as FormatAlignCenterIcon,
  FormatAlignLeft as FormatAlignLeftIcon,
  FormatAlignRight as FormatAlignRightIcon,
  FormatAlignJustify as FormatAlignJustifyIcon,
  Link as LinkIcon,
  LinkOff as LinkOffIcon,
  AddLink as AddLinkIcon,
  YouTube as YoutubeIcon,
  Title as TextIcon,
  Code as CodeBlockIcon,
  ArrowDropDown as ArrowDropDownIcon,
  Crop as CropIcon,
  MoreHoriz as MoreHorizIcon,
  Download as DownloadIcon,
  PhotoLibrary as PhotoLibraryIcon,
  PhotoLibraryOutlined as PhotoLibraryOlIcon,
  Photo as PhotoIcon,
  PhotoOutlined as PhotoOlIcon,
  Share as ShareIcon,
  EmojiEmotions as EmojiIcon,
  EmojiEmotionsOutlined as EmojiOlIcon,
  Stars as StarCircleIcon,
  Storefront as ShopIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  SwapVert as SortIcon,
  FilterAltOutlined as FilterOlIcon,
  TipsAndUpdates as TipsAndUpdatesIcon,
  DarkMode as DarkModeIcon,
  BrightnessHigh as LightModeIcon,
  Campaign as CampaignIcon,
  Twitter as TwitterIcon,
  AutoAwesome as AwesomeIcon,
  Ballot as PollIcon,
  BallotOutlined as PollOlIcon,
  ContentCopy as CopyIcon,
  ColorLens as PaletteIcon,
  ColorLensOutlined as PaletteOlIcon,
  Language as LanguageIcon,
} from "@mui/icons-material";

export {
  EditIcon,
  EditOlIcon,
  PostIcon,
  PostOlIcon,
  VoteIcon,
  VoteOlIcon,
  CommentIcon,
  CommentOlIcon,
  DeleteIcon,
  DeleteOlIcon,
  StarIcon,
  StarOlIcon,
  PostAddIcon,
  PhotoAddIcon,
  VideoAddIcon,
  CircleIcon,
  CircleOlIcon,
  ImageIcon,
  ImageOlIcon,
  RecentIcon,
  PastIcon,
  NestedIcon,
  BackIosIcon,
  ForwardIosIcon,
  InfoIcon,
  InfoOlIcon,
  HomeIcon,
  HomeOlIcon,
  DashboardIcon,
  DashboardOlIcon,
  PinIcon,
  PinOlIcon,
  HelpIcon,
  HelpOlIcon,
  VideoIcon,
  VideoOlIcon,
  ScrollTopIcon,
  CheckCircleIcon,
  CheckCircleOlIcon,
  PlayCircleOlIcon,
  GroupIcon,
  GroupOlIcon,
  BookmarkIcon,
  BookmarkOlIcon,
  UnbookmarkOlIcon,
  ReplyIcon,
  ThumbUpIcon,
  ThumbUpOlIcon,
  ThumbDownIcon,
  ThumbDownOlIcon,
  ArrowBackIcon,
  SendIcon,
  CalendarIcon,
  LiveChatIcon,
  FormatBoldIcon,
  FormatUnderlinedIcon,
  FormatItalicIcon,
  FormatStrikeIcon,
  FormatQuoteIcon,
  FormatListButlletIcon,
  FormatListNumberIcon,
  FormatAlignCenterIcon,
  FormatAlignLeftIcon,
  FormatAlignRightIcon,
  FormatAlignJustifyIcon,
  AddLinkIcon,
  LinkIcon,
  LinkOffIcon,
  YoutubeIcon,
  TextIcon,
  CodeBlockIcon,
  ArrowDropDownIcon,
  CropIcon,
  MoreHorizIcon,
  DownloadIcon,
  PhotoLibraryIcon,
  PhotoLibraryOlIcon,
  PhotoIcon,
  PhotoOlIcon,
  ShareIcon,
  EmojiIcon,
  EmojiOlIcon,
  StarCircleIcon,
  ShopIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  SortIcon,
  FilterOlIcon,
  TipsAndUpdatesIcon,
  DarkModeIcon,
  LightModeIcon,
  CampaignIcon,
  TwitterIcon,
  AwesomeIcon,
  PollIcon,
  PollOlIcon,
  CopyIcon,
  PaletteIcon,
  PaletteOlIcon,
  LanguageIcon,
};
